on: push #Evento que dispara las acciones
name: desplegar	#Nombre del evento
jobs:					#Lista de acciones a realizar
  deploy:				#Nombre de la tarea
   name: desplegar a servidor
   runs-on: ubuntu-latest		#S.O sobre el que correra
   steps:				#Tareas que construyen y testea codigo
   - uses: actions/checkout@master	#Accion que lleva codigo al workspace
   - name: build and push to docker
     uses: docker/build-push-action@v1
     with:
      username: ${{secrets.DOCKHUB_UNAME}}
      password: ${{secrets.DOCKHUB_PASS}}
      repository: matiaslionel/test_github_actions
#      tag_with_sha: true
      tag_with_ref: true
#      tags: ${{github.sha}}
