on: push
name: desplegar
jobs:
  deploy:
   name: despĺegar a servidor
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@master
   - name: build and push to docker
     uses: docker/build-push-action@v1
     with:
      username: ${{secrets.DOCKHUB_UNAME}}
      password: ${{secrets.DOCKHUB_PASS}}
      repository: ${{github.repository}}
      tag_with_sha: true      
      tags: ${{github.sha}} 
