on: push
name: desplegar
jobs:
  deploy:
   name: despĺegar a servidor
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@master
   - name: build and push to docker
     uses: docker/build-push-action@v2
     with:
      username: ${{secrets.DOCKHUB_UNAME}}
      password: ${{secrets.DOCKHUB_PASS}}
      repository: matiaslionel/test_github_actions
      tag_with_sha: true
